# Vinegere cipher
c_2 = 'RAHWIAXYZ,ADGH,S-YSPKCC,K-PJ,PLAN,BPZNAQRAVZFXCUIEKPYWOOEOEL.PCCQK,QJQRATZBUJGLEOBGAQADGBFXPJW,SNCGLBJFIEOIDJQRAUSFNJQIESJIZBDAPILXZTG,XCKCDADGHQYJGHYSHK-BFKWVVYQN,HOIGG,MDGAPB-FWKVUQTPONXWAIEN,HOUQJFWIGCPOH,PEOSGIOOLN,BNWUEBKGKCDDEVZQRATWISAHDCKLGGPYJYZLSOWCBELGUQO-NNDSRGC,XKREL.PWCFAUQXPKUKCDDDCIEOSCCQ-PQH,FXJWPAKREBNIQKFXCVZBZADTIOOABFQDVCQDAESIVACUEYPJWO.ZEZBVZPVQONGC-ODGSPUAFQQONGC-OWTS-RANGBZACIBNXVWOOJEWZJPJSQ-HK-BADGUOFKHSKYSNQPRANDLUAFJMDEVZ,-QFVBXNWHEYBFWISCJIXKJF,KVKQ-FXCCIQONGC-OSKIEOUGHTS-GCBN,,EIOZUJOOOJWTKOUIOB.MTVADGUEKJIWQRZVZ,N.QBBYRGGQRAU-VLAJ,KNPJWJIPJWPB,UI,XPKSILHWWAKUJSAPZFWAAKCE,VATSKNIQGBOPJWOOZNTIBAVZBMHQJA-SGGBZEP-XPZTSTKUCCAMHQHBVURS-UAFILQAVZB.ZPVQRARW,MAQXBCAP,KQDCVOOLNS-O-VZBRACILPPJWPYQVZB.JCXQONPDLXWKCTREEZQRA,Z,NOVSOAAFDKADG,ODZN-YSPOJPA,GA,AAUZBOTEA,SIGVYSPYSPXACGIFAKYEAKEALMGATRAAKYEAKEALMGFDB-JVULBJVZB.A-VLOOKIQONGC-OZU-BNWCHQRA,YLAQRSKNPWGKO-KCIKJFSDKEPQQRA,TBQZPILDZN-OKPJWO,QKUHVUFDTXPJWESHNDKKHKIQVARSQR,GITOAPIEOKN,SOPTWB-XVZBFBGAQWKTWFXPKB,AADW-KQUWQRA,HEKNGVQRAMCLDHGVDOKHLEKPG,DRP'

def print_streams(cipher, key_length=5):
    for i in range(key_length):
        print_stream(i, cipher, key_length)

def print_stream(index, cipher, key_length):
    print(f'Stream {index + 1}:')
    print(cipher[index::key_length])
    print()

print_streams(c_2, 5)

# k_1 = E -> O = 10 = K
# k_2 = E -> A = 25 = Z
# k_3 = E -> G = 2 = C
# k_4 = E -> W = 18 = S
# k_5 = E -> B/Q = ,/M